#!/usr/bin/env python3
"""Generates protocol constants for Lua, Python and TypeScript from protocol.schema.json, and
the skills registry from skills.json: the hub's rows (supabase/seed/skills.sql), the parameter
bounds the bus checks (Lua), and the full registry for the companion and the dashboard.

    python packages/protocol/codegen.py           write the generated files
    python packages/protocol/codegen.py --check   fail if they are out of date (for CI)

Never edit the generated files by hand; change the schema and run this.
"""

from __future__ import annotations

import argparse
import json
import pprint
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
SCHEMA = HERE / "protocol.schema.json"
SKILLS = HERE / "skills.json"
LUA_OUT = ROOT / "lua" / "autoconf" / "custom" / "dufleet" / "protocol_gen.lua"
PY_OUT = ROOT / "companion" / "src" / "dufleet" / "protocol" / "generated.py"
TS_OUT = ROOT / "dashboard" / "lib" / "protocol.ts"
SQL_OUT = ROOT / "supabase" / "seed" / "skills.sql"

HEADER = "Generated by packages/protocol/codegen.py from packages/protocol/protocol.schema.json. Do not edit."
SQL_HEADER = "Generated by packages/protocol/codegen.py from packages/protocol/skills.json. Do not edit."


def load() -> dict:
    return json.loads(SCHEMA.read_text(encoding="utf-8"))


def load_skills(schema: dict) -> dict:
    """skills.json without its comment, checked against the protocol: every skill is one `run` accepts."""
    skills = {k: v for k, v in json.loads(SKILLS.read_text(encoding="utf-8")).items() if not k.startswith("$")}
    for name, skill in skills.items():
        if name not in schema["x-protocol"]["skills"]:
            raise SystemExit(f"skills.json: {name} is not in x-protocol.skills")
        skill.pop("examples", None)  # fixtures for the tests, not part of the registry
        unknown = set(skill["required"]) - set(skill["params"])
        if unknown:
            raise SystemExit(f"skills.json: {name} requires unknown params {sorted(unknown)}")
        for param, spec in skill["params"].items():
            if spec["type"] not in ("string", "number"):
                raise SystemExit(f"skills.json: {name}.{param} must be a string or a number")
    return skills


def args_schema(skill: dict) -> dict:
    """The JSON Schema of a skill's parameters, as the hub stores it for the planner."""
    return {"type": "object", "properties": skill["params"], "required": skill["required"],
            "additionalProperties": False}


def skill_params(skills: dict) -> dict:
    """What the bus checks: which parameters exist, which are required, number bounds and defaults."""
    out = {}
    for name, skill in skills.items():
        out[name] = {}
        for param, spec in skill["params"].items():
            entry = {"required": param in skill["required"]}
            for key, lua_key in (("minimum", "min"), ("maximum", "max"), ("default", "default")):
                if key in spec:
                    entry[lua_key] = spec[key]
            out[name][param] = entry
    return out


def constants(schema: dict) -> dict:
    p = schema["x-protocol"]
    return {
        "VERSION": p["version"],
        "PREFIX": p["prefix"],
        "COMMAND_PREFIX": p["command_prefix"],
        "MAXLINE_DEFAULT": p["maxline_default"],
        "COMMAND_MAX": p["command_max"],
        "MAX_CHUNKS": p["max_chunks"],
        "MIN_CHUNK": p["min_chunk"],
        "REPLAY_RING": p["replay_ring"],
        "REASSEMBLY_TTL_S": p["reassembly_ttl_s"],
        "HELLO_INTERVAL_S": p["hello_interval_s"],
        "EPOCH_MAX": p["epoch_max"],
        "CSEQ_MAX": p["cseq_max"],
        "SEQ_MAX": p["seq_max"],
        "INBOX_MODULE": p["inbox_module"],
        "ACK_TIMEOUT_S": dict(sorted(p["ack_timeout_s"].items())),
        "RETRY_BACKOFF_S": list(p["retry_backoff_s"]),
        "KINDS": dict(sorted(p["kinds"].items())),
        "PRIORITY": dict(sorted(p["priority"].items())),
        "REPLAYABLE": sorted(p["replayable"]),
        "ERRORS": dict(sorted(p["errors"].items())),
        "SKILLS": list(p["skills"]),
        "ARG_TYPES": dict(sorted(p["arg_types"].items())),
        "VERBS": {name: p["verbs"][name] for name in sorted(p["verbs"])},
        "KIND_BODIES": dict(sorted(schema["x-kind-bodies"].items())),
    }


# --- Lua -------------------------------------------------------------------------

SETS = {"REPLAYABLE", "SKILLS"}  # also emitted as membership tables


def lua_str(s: str) -> str:
    out = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{out}"'


def lua_value(v, indent: int) -> str:
    pad, inner = "    " * indent, "    " * (indent + 1)
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, str):
        return lua_str(v)
    if isinstance(v, list):
        if not v:
            return "{}"
        if all(not isinstance(x, (dict, list)) for x in v):
            return "{ " + ", ".join(lua_value(x, 0) for x in v) + " }"
        return "{\n" + "".join(f"{inner}{lua_value(x, indent + 1)},\n" for x in v) + pad + "}"
    if isinstance(v, dict):
        if not v:
            return "{}"
        # ["key"] form everywhere: "goto" is a reserved word in Lua 5.3
        items = "".join(f"{inner}[{lua_str(k)}] = {lua_value(x, indent + 1)},\n" for k, x in v.items())
        return "{\n" + items + pad + "}"
    raise TypeError(f"cannot emit {type(v)}")


def render_lua(c: dict) -> str:
    lines = [f"-- {HEADER}", "return {"]
    for key, value in c.items():
        if key in SETS:
            lines.append(f"    {key}_LIST = {lua_value(value, 1)},")
            lines.append(f"    {key} = {lua_value({k: True for k in value}, 1)},")
        else:
            lines.append(f"    {key} = {lua_value(value, 1)},")
    lines.append("}")
    return "\n".join(lines) + "\n"


# --- Python ----------------------------------------------------------------------


def render_py(c: dict, schema: dict) -> str:
    lines = [f'"""{HEADER}"""', "", "# ruff: noqa: E501", ""]
    # Frame body schemas, for validation in the companion. The bus never needs them.
    c = {**c, "BODY_DEFS": schema["$defs"]}
    for key, value in c.items():
        if key in SETS:
            value = tuple(value)
        elif key == "RETRY_BACKOFF_S":
            value = tuple(value)
        text = pprint.pformat(value, width=110, sort_dicts=False)
        lines.append(f"{key} = {text}")
    return "\n".join(lines) + "\n"


# --- TypeScript (dashboard) ------------------------------------------------------


def render_sql(skills: dict) -> str:
    def lit(value) -> str:
        text = value if isinstance(value, str) else json.dumps(value, ensure_ascii=False)
        if "$skill$" in text:
            raise SystemExit("skills.json: text may not contain $skill$")
        return f"$skill${text}$skill$" + ("" if isinstance(value, str) else "::jsonb")

    rows = ",\n".join(
        f"  ({lit(name)}, {lit(s['version'])}, {lit(args_schema(s))},\n   {lit(s['description'])},\n"
        f"   {lit(s['preconditions'])},\n   {lit(s['postconditions'])})"
        for name, s in skills.items())
    names = ", ".join(lit(name) for name in skills)
    return (f"-- {SQL_HEADER}\n"
            "-- Apply after the migrations, and again whenever skills.json changes. Rows are updated in place,\n"
            "-- keeping their success and failure counts; skills no longer in skills.json are removed.\n"
            "insert into public.skills (name, version, args_schema, description, preconditions, postconditions)"
            f" values\n{rows}\n"
            "on conflict (name) do update set version = excluded.version, args_schema = excluded.args_schema,\n"
            "  description = excluded.description, preconditions = excluded.preconditions,\n"
            "  postconditions = excluded.postconditions;\n"
            f"delete from public.skills where name not in ({names});\n")


def render_ts(c: dict) -> str:
    lines = [f"// {HEADER}", ""]
    for key, value in c.items():
        lines.append(f"export const {key} = {json.dumps(value, indent=2)} as const;")
        lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail if generated files are out of date")
    args = parser.parse_args(argv)
    schema = load()
    c = constants(schema)
    skills = load_skills(schema)
    registry = {name: {"version": s["version"], "description": s["description"], "args_schema": args_schema(s),
                       "preconditions": s["preconditions"], "postconditions": s["postconditions"]}
                for name, s in skills.items()}
    outputs = {
        LUA_OUT: render_lua({**c, "SKILL_PARAMS": skill_params(skills)}),
        PY_OUT: render_py({**c, "SKILL_REGISTRY": registry}, schema),
        TS_OUT: render_ts({**c, "SKILL_REGISTRY": registry}),
        SQL_OUT: render_sql(skills),
    }
    stale = []
    for path, text in outputs.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        if args.check:
            stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        for path in stale:
            print(f"out of date: {path.relative_to(ROOT)}", file=sys.stderr)
        print("run: python packages/protocol/codegen.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
