-- Generated by packages/protocol/codegen.py from packages/protocol/skills.json. Do not edit.
-- Apply after the migrations, and again whenever skills.json changes. Rows are updated in place,
-- keeping their success and failure counts; skills no longer in skills.json are removed.
insert into public.skills (name, version, args_schema, description, preconditions, postconditions) values
  ($skill$goto$skill$, $skill$1$skill$, $skill${"type": "object", "properties": {"pos": {"type": "string", "maxLength": 120, "pattern": "^[0-9]+,[0-9]+,[+-]?[0-9]+(\\.[0-9]+)?([eE][+-]?[0-9]+)?,[+-]?[0-9]+(\\.[0-9]+)?([eE][+-]?[0-9]+)?,[+-]?[0-9]+(\\.[0-9]+)?([eE][+-]?[0-9]+)?$", "description": "systemId,bodyId,lat,lon,alt as in ::pos: degrees and metres above sea level. Body 0 is deep space, with world x,y,z in place of lat,lon,alt"}, "tol": {"type": "number", "minimum": 1, "maximum": 100000, "description": "arrival tolerance in metres: horizontal on a planet; in space, straight and beyond the AutopilotSpaceDistance that ArchHUD stops short of the target (5000 m by default). Default 50 on a planet and 1000 in space"}, "timeout": {"type": "number", "minimum": 10, "maximum": 86400, "default": 3600, "description": "seconds of running time, pauses excluded, before the job gives up"}}, "required": ["pos"], "additionalProperties": false}$skill$::jsonb,
   $skill$Fly to a position with ArchHUD's autopilot and stop there: it lands under the target on a planet, and stops near it in space.$skill$,
   $skill$["ArchHUD has finished starting", "no ArchHUD travel mode is set and no ArchHUD route is loaded", "the fuel the trip needs is above dub.cfg.minfuel (10%)", "the target body is in ArchHUD's atlas"]$skill$::jsonb,
   $skill$["done: the ship has stood still for 5 s within tol of the target", "cancelled, timed out, or failed on the way: the autopilot is off, the throttle is 0 and the brake is set"]$skill$::jsonb)
on conflict (name) do update set version = excluded.version, args_schema = excluded.args_schema,
  description = excluded.description, preconditions = excluded.preconditions,
  postconditions = excluded.postconditions;
delete from public.skills where name not in ($skill$goto$skill$);
