-- Generated by packages/protocol/codegen.py from packages/protocol/protocol.schema.json. Do not edit.
return {
    VERSION = 1,
    PREFIX = "@@DUB",
    COMMAND_PREFIX = "/b ",
    MAXLINE_DEFAULT = 400,
    COMMAND_MAX = 240,
    MAX_CHUNKS = 99,
    MIN_CHUNK = 16,
    REPLAY_RING = 32,
    REASSEMBLY_TTL_S = 10,
    HELLO_INTERVAL_S = 30,
    EPOCH_MAX = 65535,
    CSEQ_MAX = 2147483647,
    SEQ_MAX = 4294967295,
    INBOX_MODULE = "autoconf/custom/dufleet/inbox",
    ACK_TIMEOUT_S = {
        ["C"] = 3,
        ["F"] = 3,
        ["L"] = 3,
        ["O"] = 5,
    },
    RETRY_BACKOFF_S = { 1, 3, 8 },
    KINDS = {
        ["A"] = "ack: the command was accepted, or is a replay of the last accepted one",
        ["D"] = "debug text",
        ["E"] = "event",
        ["H"] = "hello: boot id, versions, epoch and command watermark; sent at start and on status",
        ["N"] = "nack: the command was refused",
        ["R"] = "result of a skill job",
        ["T"] = "telemetry: the latest state; fire and forget, only the newest is kept",
    },
    PRIORITY = {
        ["A"] = 0,
        ["D"] = 3,
        ["E"] = 1,
        ["H"] = 1,
        ["N"] = 0,
        ["R"] = 1,
        ["T"] = 2,
    },
    REPLAYABLE_LIST = { "A", "E", "N", "R" },
    REPLAYABLE = {
        ["A"] = true,
        ["E"] = true,
        ["N"] = true,
        ["R"] = true,
    },
    ERRORS = {
        ["E_ARGS"] = "arguments invalid",
        ["E_BUSY"] = "another job is running",
        ["E_CRC"] = "command CRC mismatch",
        ["E_EPOCH"] = "command from an older epoch",
        ["E_FUEL"] = "not enough fuel",
        ["E_INTERNAL"] = "bus error; see D frames",
        ["E_LINK"] = "a required element is not linked",
        ["E_PARSE"] = "command line malformed",
        ["E_STATE"] = "not possible in the current state, or superseded by a newer command",
        ["E_VERB"] = "unknown or unavailable verb",
    },
    SKILLS_LIST = { "goto", "haul_route", "industry", "patrol", "mine_loop" },
    SKILLS = {
        ["goto"] = true,
        ["haul_route"] = true,
        ["industry"] = true,
        ["patrol"] = true,
        ["mine_loop"] = true,
    },
    ARG_TYPES = {
        ["b64"] = "^[A-Za-z0-9+/]+={0,2}$",
        ["bot"] = "^[A-Za-z0-9_-]{1,16}$",
        ["chan"] = "^[!$-\\[\\]-~]{1,64}$",
        ["dbkey"] = "^dub\\.[a-z0-9_.]{1,40}$",
        ["job"] = "^j_[A-Za-z0-9]{1,16}$",
        ["kv"] = "^[a-z][a-z0-9_]{0,15}=[!$-\\[\\]-~]{1,120}$",
        ["text"] = "^[!$-\\[\\]-~]{1,200}$",
        ["uint"] = "^(0|[1-9][0-9]{0,9})$",
    },
    VERBS = {
        ["cal"] = {
            ["doc"] = "optical calibration pattern on or off (Transport O)",
            ["args"] = {
                {
                    ["name"] = "state",
                    ["type"] = "enum",
                    ["values"] = { "on", "off" },
                },
            },
        },
        ["cancel"] = {
            ["doc"] = "stop the running job and brake",
            ["args"] = {
                {
                    ["name"] = "job",
                    ["type"] = "job",
                    ["optional"] = true,
                },
            },
        },
        ["db"] = {
            ["doc"] = "read, write or delete one dub. databank key",
            ["args"] = {
                {
                    ["name"] = "op",
                    ["type"] = "enum",
                    ["values"] = { "get", "set", "del" },
                },
                {
                    ["name"] = "key",
                    ["type"] = "dbkey",
                },
                {
                    ["name"] = "value",
                    ["type"] = "text",
                    ["optional"] = true,
                },
            },
        },
        ["pause"] = {
            ["doc"] = "hold the running job",
            ["args"] = {},
        },
        ["ping"] = {
            ["doc"] = "acknowledge only",
            ["args"] = {},
        },
        ["relay"] = {
            ["doc"] = "Phase 3: forward a payload to a worker board over the emitter",
            ["args"] = {
                {
                    ["name"] = "chan",
                    ["type"] = "chan",
                },
                {
                    ["name"] = "payload",
                    ["type"] = "b64",
                },
            },
        },
        ["resend"] = {
            ["doc"] = "send replayable frames with seq >= from again",
            ["args"] = {
                {
                    ["name"] = "from",
                    ["type"] = "uint",
                },
            },
        },
        ["resume"] = {
            ["doc"] = "continue a paused job",
            ["args"] = {},
        },
        ["run"] = {
            ["doc"] = "start a skill job",
            ["args"] = {
                {
                    ["name"] = "skill",
                    ["type"] = "skill",
                },
                {
                    ["name"] = "job",
                    ["type"] = "job",
                },
                {
                    ["name"] = "params",
                    ["type"] = "kv",
                    ["variadic"] = true,
                },
            },
        },
        ["setid"] = {
            ["doc"] = "store the bot id in the databank",
            ["args"] = {
                {
                    ["name"] = "id",
                    ["type"] = "bot",
                },
            },
        },
        ["status"] = {
            ["doc"] = "acknowledge, then send H and T",
            ["args"] = {},
        },
    },
    KIND_BODIES = {
        ["A"] = "ack",
        ["D"] = "debug",
        ["E"] = "event",
        ["H"] = "hello",
        ["N"] = "nack",
        ["R"] = "result",
        ["T"] = "telemetry",
    },
}
